### ISSUE TITLE
[BUG] image not visible

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#110]
**Describe the bug**
Sometimes, if you send an image-link, the chat doesn't scrolls up

**Expected behavior**
Image should be fully visible

**Screenshots**
Will be added

**Used Browser**
Chrome, Firefox

**Comment by Monkmitrad** [comment]
Image loads after div has been given it's needed space, so the image is clipping the given space
Solution would be the image.onLoadEventHandler

**Comment by Monkmitrad** [comment]
only appears, when image is new and not already cached

**Comment by SFFan123** [comment]
maybe add a timeout after that the autoscroll gets triggered?

**Comment by SFFan123** [comment]
image event listner for load img.onload?
