### ISSUE TITLE
[BUG]tabs in CodeBlocks 

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#178]
**Describe the bug**
tabs in issue get removed by regex

**Expected behavior**
tabs in code blocks should be visible

**Used Browser**
all browsers

**Comment by SFFan123** [comment]
partially fixed in #191

**Comment by SFFan123** [comment]
next step make it possible to insert \t by keyboard

**Comment by SFFan123** [comment]
fixed with #197
