### ISSUE TITLE
Replace IP-Address with timestamp for message.

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#2]
IP-address of every client is loopback

**Comment by SFFan123** [comment]
Was for internal usage, it showed the NT-User back then. Now it can be replaced with a Timestamp...

**Comment by SFFan123** [comment]
gets fixed in -> https://github.com/FI18-Trainees/FISocketChat/tree/replace-IP-with-username
PR ->https://github.com/FI18-Trainees/FISocketChat/pull/11
