### ISSUE TITLE
Embeds à la Discord

### ISSUE THREAD

**Issue by zaanposni** [FI18-Trainees/FISocketChat#202]
Implement embeds to print detailed and beautiful messages.
@Monkmitrad or someonelese has to implement css/html for that
I would provide a object similiar to discord format.

Embeds should only be sendable for commands or serverside

For a detailed and visualized example for discord embeds object see:
[https://leovoel.github.io/embed-visualizer/](https://leovoel.github.io/embed-visualizer/)
Example: 
![grafik](https://user-images.githubusercontent.com/24491035/68773317-a502b580-062b-11ea-84ed-1150903ddbc3.png)

Feel free to tell me how you feel about that.

**Comment by Monkmitrad** [comment]
what kind of content, do you want to embed? @zaanposni

**Comment by zaanposni** [comment]
You can expect:
- Author info
- Thumbnail
- Text
- Media
- footer 
- Timestamp

Media includes:
Direct links to media and a attribute which media type it is ( img / audio / video ) 

Note that each named thing can be „None“ except the main text. 
@MonkMitRad

**Comment by zaanposni** [comment]
For further docu see: https://github.com/FI18-Trainees/FISocketChat/blob/master/src/app/obj/embed.py#L38
