### ISSUE TITLE
[BUG] gitversion first part of link wrong

### ISSUE THREAD

**Issue by zaanposni** [FI18-Trainees/FISocketChat#220]
**Describe the bug**
/gitversion redirects to:
https://chat.zaanposni.com/git@github.com:FI18-Trainees/FISocketChat/commits/923d9e0e5882e3273cc56a3e55c291b565a1a2f9

**Expected behavior**
correct link

**Used Browser**
unrelated

**Additional context**
hardcode the first part of the url ?

**Comment by SFFan123** [comment]
no because you use SSH and the gitversion was developed for https...
adding ssh support now.
