### ISSUE TITLE
[BUG]local test not possible

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#36]
**Describe the bug**
error message reffering to message handling while connecting with client onto locally started server out of optimization branch with login disabled

**Screenshots**
[pastebin](https://pastebin.com/mfmUkE10)

**Comment by zaanposni** [comment]
I cannot reproduce this error. 
- Are you on master? 
- Are your libs up to date?
- Are you starting the app with our provided startscripts ?
- What is your message content? 
- Can you debug it and check what the server receives (before he tries to convert the json)?

**Comment by Monkmitrad** [comment]
- Im on "optimization" branch, which worked at work (LuL)
- Libs are up to date
- i use win_start.bat with -disablelogin argument
- i have no message content, cause client just wants to connect and has no message provided yet
- i will try to

**Comment by Monkmitrad** [comment]
i fixed issue in my firefox-css branch
