### ISSUE TITLE
[BUG] First message after connection

### ISSUE THREAD

**Issue by zaanposni** [FI18-Trainees/FISocketChat#40]
**Describe the bug**
First message never shows up for the sender himself but for everyone else.

**Expected behavior**
Every message should be visible.
Only allow sending messages as the connection is established properly?

**Used Browser**
Chrome and Firefox

**Comment by zaanposni** [comment]
Maybe this is a css related issue? Appears that the first message is just behind our banner :D

**Comment by Monkmitrad** [comment]
can't reproduce this error

**Comment by zaanposni** [comment]
is irregular and can be attributed to nothing so I am closing this
