### ISSUE TITLE
Restore header

### ISSUE THREAD

**Issue by SFFan123** [FI18-Trainees/FISocketChat#53]
```<i class="fab fa-skype fa-spin d-inline-block align-top" style="color: #00aff0" title="Skype rotiert"></i> Super cheap chat with sock(et)?s <i class="fas fa-socks"></i>``` is required in the header!

**Comment by zaanposni** [comment]
🤣

**Comment by ArPiiX** [comment]
added bug label as it seems to need a fix in order for skype symbol to be shown again
