### ISSUE TITLE
[BUG] Firefox scroll bug on emoji pickup

### ISSUE THREAD

**Issue by zaanposni** [FI18-Trainees/FISocketChat#61]
**Describe the bug**
After I select a emoji from the emoji menu, the browser scrolls up.

**Expected behavior**
No additonal scrolling as in chrome

**Used Browser**
Only occurres in firefox

**Comment by Monkmitrad** [comment]
Cannot reproduce this error.
Do you use Firefox in Fullscreen mode?

**Comment by Monkmitrad** [comment]
does this happen, if u test it locally?

**Comment by zaanposni** [comment]
I was able to reproduce this @home, it always scrolls up to the top of the chat. 😕
