### ISSUE TITLE
[BUG]emoji menu not completely visible if not in fullscreen

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#62]
**Describe the bug**
The emoji menu is partly cut off, if the browser is not maximized.

**Expected behavior**
Emoji menu should be completely visible above button

**Used Browser**
Firefox, Chrome

**Comment by Monkmitrad** [comment]
this happens, if the menu has not enough space ontop of the button.

**Comment by zaanposni** [comment]
can reproduce this +1
