### ISSUE TITLE
CSS in small windows

### ISSUE THREAD

**Issue by ArPiiX** [FI18-Trainees/FISocketChat#69]
When dragging a browser to a smaller window size the navbar no longer shows all its content.

Maybe we need a js to remove the Text in the header to make space for a different style of navbar when using smaller windows.

**Comment by Monkmitrad** [comment]
Can you provide screenshots please?

**Comment by ArPiiX** [comment]
![image](https://user-images.githubusercontent.com/48033823/65834942-a462c980-e2e0-11e9-8051-37b0728e1a13.png)

**Comment by Monkmitrad** [comment]
I can reproduce this issue, I will look into that.
Maybe some CSS should be enough

**Comment by Monkmitrad** [comment]
will be implemented with #113
