### ISSUE TITLE
remove username input

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#87]
username cannot be chosen, so field isn't necessary anymore

**Comment by Monkmitrad** [comment]
In logindisabled-mode, username is still used, what shall we do @zaanposni ?
I think for logindisabled-mode we shall use a standard-name like "shawn".

**Comment by zaanposni** [comment]
Login **disabled**:
- Use a username field and leave the chat as it is
---
Login **enabled**:
- Do not show the username field and use the `display_name` set in the userconfig
- If the display name is invalid (e.g. a empty string or just spaces) show the `username`

Use:
`socketio.server.environ[request.sid]["userconfig"]["display_name"]` and
`socketio.server.environ[request.sid]["username"]`

**Comment by Monkmitrad** [comment]
sounds good
