### ISSUE TITLE
[BUG] Chat doesn't work in Chrome

### ISSUE THREAD

**Issue by Monkmitrad** [FI18-Trainees/FISocketChat#9]
**Describe the bug**
Chat doesn't work properly in Chrome.
Messages from others are shown, but no messages are submittable.

**Expected behavior**
Chat should work like in Firefox

**Screenshots**
n.a.

**Used Browser**
Google Chrome Version 77.0.3865.75 (Official Build) 64-bit

**Additional context**
Presumption of @zaanposni is a JavaScript-Issue, because Server shows "Bad Request" Errors.

**Comment by SFFan123** [comment]
https://github.com/socketio/socket.io/issues/1942
